FROM node:16-alpine3.14 as builder

WORKDIR /app

COPY package.json .
COPY . /app

RUN npm run build

FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app/package.json .

EXPOSE 3333

COPY --from=builder /app/dist ./dist

CMD ["node","dist/main.js"]
